baseurl = "/"
languageCode = "zh-cn"
title = "pokon548 的个人博客"
theme = "terminal"
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.cn]
    languageName = "Chinese"
    title = "pokon548 的个人博客"
    subtitle = "不拘于形，游刃有余"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "展示更多"
    readMore = "阅读更多"
    readOtherPosts = "阅读其它贴"
    missingContentMessage = "找不到页面..."
    missingBackButtonLabel = "回到主页"

    [languages.en.params.logo]
      logoText = "pokon548@blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "友链"
        url = "/links" 
